<?php

namespace App\Support\PeopleImport;

/**
 * Maps between the Students admin page's create-dialog fields and the flat
 * spreadsheet row shape used for CSV/XLSX import. Validation here mirrors
 * StudentController::validated() so an imported row can't create a student
 * with data the manual "Add New Student" dialog would have rejected —
 * faculty/department/major/promotion/stage/academic_year/semester/term/shift
 * are all required there, so they're required here too.
 *
 * Username is generated by the importing controller, not read from the
 * file. Password is optional in the file — if a row leaves it blank, the
 * controller falls back to using the student's own code, same as before.
 * Class assignment is a separate step (the page's "Assign Class" action),
 * same as manual creation.
 */
class StudentRowMapper
{
    public static function headers(): array
    {
        return [
            'code', 'password', 'name_en', 'name_kh', 'gender', 'dob', 'phone', 'address',
            'faculty', 'department', 'major', 'promotion', 'stage',
            'academic_year', 'semester', 'term', 'shift', 'status',
        ];
    }

    public static function sampleRows(): array
    {
        $common = [
            'faculty' => 'e.g. Faculty of Engineering',
            'department' => 'e.g. Computer Science',
            'major' => 'e.g. Software Engineering',
            'promotion' => 'e.g. Promotion 19',
            'stage' => 'e.g. Year 1',
            'academic_year' => 'e.g. 2025-2026',
            'semester' => 'e.g. Semester 1',
            'term' => 'e.g. Term 1',
            'shift' => 'e.g. Morning',
        ];

        return [
            $common + [
                'code' => 'STU-1001', 'password' => '', 'name_en' => 'Sok Visal', 'name_kh' => 'សុខ វិសាល',
                'gender' => 'Male', 'dob' => '2002-03-10', 'phone' => '012345678',
                'address' => 'Phnom Penh', 'status' => 'Active',
            ],
            $common + [
                'code' => 'STU-1002', 'password' => 'MySecret123', 'name_en' => 'Chan Dara', 'name_kh' => '',
                'gender' => 'Female', 'dob' => '', 'phone' => '098765432',
                'address' => '', 'status' => 'Active',
            ],
        ];
    }

    /**
     * Parse one spreadsheet row. Returns null for a blank/instructional row
     * (no code and no name) rather than an error.
     */
    public static function fromRow(array $row): ?array
    {
        $row = array_change_key_case($row, CASE_LOWER);
        $code = trim((string) ($row['code'] ?? ''));
        $nameEn = trim((string) ($row['name_en'] ?? ''));

        if ($code === '' && $nameEn === '') {
            return null;
        }

        return [
            'code' => $code,
            'password' => trim((string) ($row['password'] ?? '')),
            'name_en' => $nameEn,
            'name_kh' => trim((string) ($row['name_kh'] ?? '')) ?: null,
            'gender' => self::normalizeGender($row['gender'] ?? ''),
            'dob' => trim((string) ($row['dob'] ?? '')) ?: null,
            'phone' => trim((string) ($row['phone'] ?? '')),
            'address' => trim((string) ($row['address'] ?? '')) ?: null,
            'faculty' => trim((string) ($row['faculty'] ?? '')),
            'department' => trim((string) ($row['department'] ?? '')),
            'major' => trim((string) ($row['major'] ?? '')),
            'promotion' => trim((string) ($row['promotion'] ?? '')),
            'stage' => trim((string) ($row['stage'] ?? '')),
            'academic_year' => trim((string) ($row['academic_year'] ?? '')),
            'semester' => trim((string) ($row['semester'] ?? '')),
            'term' => trim((string) ($row['term'] ?? '')),
            'shift' => trim((string) ($row['shift'] ?? '')),
            'status' => self::normalizeStatus($row['status'] ?? ''),
        ];
    }

    /**
     * Business-rule validation matching StudentController::validated()'s
     * required fields. Returns a list of human-readable error strings;
     * empty means valid. Foreign-key names are resolved and checked
     * separately by the importing controller, which has DB access.
     */
    public static function validate(array $parsed): array
    {
        $errors = [];

        if ($parsed['code'] === '') {
            $errors[] = 'Missing student ID.';
        }

        if ($parsed['name_en'] === '') {
            $errors[] = 'Missing name.';
        }

        if ($parsed['password'] !== '' && strlen($parsed['password']) < 8) {
            $errors[] = 'Password must be at least 8 characters.';
        }

        if (! in_array($parsed['gender'], ['Male', 'Female'], true)) {
            $errors[] = 'Gender must be Male or Female.';
        }

        if ($parsed['phone'] === '') {
            $errors[] = 'Missing phone number.';
        }

        foreach (['faculty', 'department', 'major', 'promotion', 'stage', 'academic_year', 'semester', 'term', 'shift'] as $field) {
            if ($parsed[$field] === '') {
                $errors[] = 'Missing '.str_replace('_', ' ', $field).'.';
            }
        }

        if (! in_array($parsed['status'], ['Active', 'Inactive', 'Suspended'], true)) {
            $errors[] = 'Status must be Active, Inactive, or Suspended.';
        }

        if ($parsed['dob'] && ! strtotime($parsed['dob'])) {
            $errors[] = 'Date of birth is not a valid date.';
        }

        return $errors;
    }

    private static function normalizeGender(mixed $value): string
    {
        return ucfirst(strtolower(trim((string) $value)));
    }

    private static function normalizeStatus(mixed $value): string
    {
        $value = trim((string) $value);

        return $value === '' ? 'Active' : ucfirst(strtolower($value));
    }
}
