<?php

namespace App\Support\PeopleImport;

/**
 * Maps between the Teachers admin page's create-dialog fields and the flat
 * spreadsheet row shape used for CSV/XLSX import. Validation here mirrors
 * TeacherController::validated() so an imported row can't create a teacher
 * with data the manual "Add New Teacher" dialog would have rejected.
 *
 * Username is generated by the importing controller, not read from the
 * file. Password is optional in the file — if a row leaves it blank, the
 * controller falls back to using the teacher's own code, same as before.
 */
class TeacherRowMapper
{
    public static function headers(): array
    {
        return [
            'code', 'password', 'name_en', 'name_kh', 'gender', 'dob', 'phone', 'address',
            'faculty', 'department', 'major', 'qualification', 'specialization',
            'type', 'hire_date', 'status',
        ];
    }

    public static function sampleRows(): array
    {
        return [
            [
                'code' => 'T-101', 'password' => '', 'name_en' => 'Sok Chantha', 'name_kh' => 'សុខ ចាន់ថា',
                'gender' => 'Male', 'dob' => '1990-05-12', 'phone' => '012345678',
                'address' => 'Phnom Penh', 'faculty' => 'e.g. Faculty of Engineering',
                'department' => '', 'major' => '', 'qualification' => 'MSc Computer Science',
                'specialization' => 'Database Systems', 'type' => 'Full-Time',
                'hire_date' => '2020-01-15', 'status' => 'Active',
            ],
            [
                'code' => 'T-102', 'password' => 'MySecret123', 'name_en' => 'Chan Sopheak', 'name_kh' => '',
                'gender' => 'Female', 'dob' => '', 'phone' => '098765432',
                'address' => '', 'faculty' => 'e.g. Faculty of Engineering',
                'department' => '', 'major' => '', 'qualification' => '',
                'specialization' => '', 'type' => 'Part-Time', 'hire_date' => '', 'status' => 'Active',
            ],
        ];
    }

    /**
     * Parse one spreadsheet row. Returns null for a blank/instructional row
     * (no code and no name) rather than an error.
     */
    public static function fromRow(array $row): ?array
    {
        $row = array_change_key_case($row, CASE_LOWER);
        $code = trim((string) ($row['code'] ?? ''));
        $nameEn = trim((string) ($row['name_en'] ?? ''));

        if ($code === '' && $nameEn === '') {
            return null;
        }

        return [
            'code' => $code,
            'password' => trim((string) ($row['password'] ?? '')),
            'name_en' => $nameEn,
            'name_kh' => trim((string) ($row['name_kh'] ?? '')) ?: null,
            'gender' => self::normalizeGender($row['gender'] ?? ''),
            'dob' => trim((string) ($row['dob'] ?? '')) ?: null,
            'phone' => trim((string) ($row['phone'] ?? '')),
            'address' => trim((string) ($row['address'] ?? '')) ?: null,
            'faculty' => trim((string) ($row['faculty'] ?? '')),
            'department' => trim((string) ($row['department'] ?? '')),
            'major' => trim((string) ($row['major'] ?? '')),
            'qualification' => trim((string) ($row['qualification'] ?? '')) ?: null,
            'specialization' => trim((string) ($row['specialization'] ?? '')) ?: null,
            'type' => self::normalizeType($row['type'] ?? ''),
            'hire_date' => trim((string) ($row['hire_date'] ?? '')) ?: null,
            'status' => self::normalizeStatus($row['status'] ?? ''),
        ];
    }

    /**
     * Business-rule validation matching TeacherController::validated()'s
     * required fields. Returns a list of human-readable error strings;
     * empty means valid. Foreign-key names (faculty/department/major) are
     * resolved and checked separately by the importing controller, which
     * has DB access.
     */
    public static function validate(array $parsed): array
    {
        $errors = [];

        if ($parsed['code'] === '') {
            $errors[] = 'Missing teacher code.';
        }

        if ($parsed['name_en'] === '') {
            $errors[] = 'Missing name.';
        }

        if ($parsed['password'] !== '' && strlen($parsed['password']) < 8) {
            $errors[] = 'Password must be at least 8 characters.';
        }

        if (! in_array($parsed['gender'], ['Male', 'Female'], true)) {
            $errors[] = 'Gender must be Male or Female.';
        }

        if ($parsed['phone'] === '') {
            $errors[] = 'Missing phone number.';
        }

        if ($parsed['faculty'] === '') {
            $errors[] = 'Missing faculty.';
        }

        if (! in_array($parsed['type'], ['Full-Time', 'Part-Time'], true)) {
            $errors[] = 'Employment type must be Full-Time or Part-Time.';
        }

        if (! in_array($parsed['status'], ['Active', 'Inactive'], true)) {
            $errors[] = 'Status must be Active or Inactive.';
        }

        if ($parsed['dob'] && ! strtotime($parsed['dob'])) {
            $errors[] = 'Date of birth is not a valid date.';
        }

        if ($parsed['hire_date'] && ! strtotime($parsed['hire_date'])) {
            $errors[] = 'Hire date is not a valid date.';
        }

        return $errors;
    }

    private static function normalizeGender(mixed $value): string
    {
        return ucfirst(strtolower(trim((string) $value)));
    }

    private static function normalizeType(mixed $value): string
    {
        $value = trim((string) $value);

        if ($value === '') {
            return 'Full-Time';
        }

        $normalized = str_replace(' ', '-', ucwords(strtolower(str_replace('-', ' ', $value))));

        return in_array($normalized, ['Full-Time', 'Part-Time'], true) ? $normalized : $value;
    }

    private static function normalizeStatus(mixed $value): string
    {
        $value = trim((string) $value);

        return $value === '' ? 'Active' : ucfirst(strtolower($value));
    }
}
